#config_version=6

slide_player:
  mode_attract_started: attract

light_player:
  mode_attract_started:
    led_gi:
      color: white
      fade: 200ms

show_player:
  mode_attract_started:
    attract_lights:
      loops: -1
      speed: 20

mode_settings:
  selectable_items:
    - gameover
    - title
  next_item_events: s_right_flipper_active, timer_carousel_timer_complete
  previous_item_events: s_left_flipper_active

timers:
  carousel_timer:
    start_value: 0
    end_value: 3
    direction: up
    restart_on_complete: true
    start_running: true
